### ISSUE TITLE
Raise exception with actual descriptive error if create_server (and other server action) fails

### ISSUE THREAD

**Issue by jcortega** [CenturyLinkCloud/clc-python-sdk#11]
Currently, the sdk raises the below error when it fails to create or powers off server:

[2015-05-29 02:32:32,257: WARNING/Worker-1] Traceback (most recent call last):
  File "/home/zenoss/zcomms/provisioner/provisioner.py", line 127, in create_instance
    api_endpoint=CTL_ENDPOINT)
  File "/home/zenoss/zcomms/utils/provisioner.py", line 99, in create_instance
    description = machine_specs['Description']
  File "/usr/lib/python2.6/site-packages/clc/APIv2/server.py", line 471, in Create
    'customFields': custom_fields, 'additionalDisks': additional_disks, 'ttl': ttl, 'packages': packages}))))
  File "/usr/lib/python2.6/site-packages/clc/APIv2/queue.py", line 49, in __init__
    if 'isQueued' in requests_lst:  requests_lst = [requests_lst]
TypeError: argument of type 'NoneType' is not iterable
[2015-05-29 02:32:32,273: INFO/MainProcess] Received task:

**Comment by jcortega** [comment]
Thanks!
