### ISSUE TITLE
ShutDown, PowerOff, PowerOn, and Pause generate exceptions if the server is already in the desired state

### ISSUE THREAD

**Issue by computergeek125** [CenturyLinkCloud/clc-python-sdk#41]
When the methods ShutDown, PowerOff, PowerOn, and Pause are used against a server that is already in the desired state, they generate a `KeyError` exception.  All methods generate the same exception.  In the following example, I was working with an interactive shell on a server that started off.  Server.Reset() behaves as expected, generating an exception describing the error.

As a temporary workaround, I can have my program catch a KeyError in addition to the clc.CLCException error handling and assume that the two represent the same problem, however, this should be fixed.

```python
>>> server.powerState
u'stopped'
>>> server.PowerOn()
<clc.APIv2.queue.Requests object at 0x6ffff321e50>
>>> server.Refresh()
>>> server.powerState
u'started'
>>> server.PowerOn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 368, in PowerOn
    def PowerOn(self):  return(self._Operation('powerOn'))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 357, in _Operation
    session=self.session))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/queue.py", line 95, in __init__
    if r['errorMessage'] == "The server already in desired state.":  pass
KeyError: 'errorMessage'
>>> server.Pause()
<clc.APIv2.queue.Requests object at 0x6ffff321f10>
>>> server.Refresh()
>>> server.powerState
u'paused'
>>> server.Pause()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 364, in Pause
    def Pause(self):  return(self._Operation('pause'))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 357, in _Operation
    session=self.session))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/queue.py", line 95, in __init__
    if r['errorMessage'] == "The server already in desired state.":  pass
KeyError: 'errorMessage'
>>> server.ShutDown()
<clc.APIv2.queue.Requests object at 0x6ffffe6f250>
>>> server.Refresh()
>>> server.powerState
u'stopped'
>>> server.ShutDown()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 365, in ShutDown
    def ShutDown(self):  return(self._Operation('shutDown'))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 357, in _Operation
    session=self.session))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/queue.py", line 95, in __init__
    if r['errorMessage'] == "The server already in desired state.":  pass
KeyError: 'errorMessage'
>>> server.PowerOff()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 369, in PowerOff
    def PowerOff(self):  return(self._Operation('powerOff'))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 357, in _Operation
    session=self.session))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/queue.py", line 95, in __init__
    if r['errorMessage'] == "The server already in desired state.":  pass
KeyError: 'errorMessage'
>>> server.Reset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 367, in Reset
    def Reset(self):  return(self._Operation('reset'))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/server.py", line 357, in _Operation
    session=self.session))
  File "/usr/lib/python2.7/site-packages/clc/APIv2/queue.py", line 101, in __init__
    raise(clc.CLCException("%s '%s' not added to queue: %s" % (context_key,context_val,r['errorMessage'])))
clc.CLCException: server '***REDACTED***' not added to queue: The operation cannot be queued for a powered off server.
```

**Comment by EfrenRey** [comment]
@computergeek125 Hi, this issue has been solved. Thanks.
